name: .NET build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Install dependencies
      working-directory: ./src/WebApi
      run: dotnet restore
    - name: Build
      working-directory: ./src/WebApi
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ./src/WebApi
      run: dotnet test