# This workflow will build and push a .NET Core app to an Azure Web App when a commit is pushed to your default branch.

name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: api-iapp-dev            # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'       # set this to the path to your web app project, defaults to the repository root

on:
  push:
    branches:
      - feature/testEnvDeployment
  workflow_dispatch:

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Set up .NET Core
  #       uses: actions/setup-dotnet@v1
  #       with:
  #         dotnet-version: 6.0.x
      
  #     - name: Set up dependency caching for faster builds
  #       uses: actions/cache@v2
  #       with:
  #         path: ~/.nuget/packages
  #         key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-nuget-

  #     - name: dotnet publish
  #       working-directory: ./src/WebApi/WebApi
  #       run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp /p:DebugType=None /p:DebugSymbols=false /p:SkipInvalidConfigurations=true

  #     - name: Upload artifact for deployment job
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: .net-app
  #         path: ${{env.DOTNET_ROOT}}/myapp

  DeployDev:
    name: Deploy to dev
    #if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    #needs: [build]
    environment: 'dev'

    steps:
      # #####################
      # # Download artifact #
      # #####################
      # - name: Download artifact from build job
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: .net-app

      # ##################
      # # Login to azure #
      # ##################
      # - name: Login to Azure
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      #     enable-AzPSSession: true

      ########
      # Test #
      ########
      - name: Test
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"
          inlineScript: |
            # Write-Output "Stop site"
            # Write-Output "Run codefirst"
            # Write-Output "Deploy"
            # Write-Output "Warm up site"
            Write-Output "Env1: ${{steps.environment.outputs.environment.name}}"
            Write-Output "Env2: $Env.name"
            Write-Output "Env3: $env.name"
            Write-Output "Env4: $Env:name"
            Write-Output "Env4: $Env:name"
            Write-Output "Env: $Env"
            Write-Output "Environment: $environment"
            Write-Output "Job=$job1"
            Write-Output "****"
            Write-Output "Job=${{ job.environment.name }}"
            Write-Output "**"
            env

      # #########################################
      # # Deploy to azure #
      # #########################################
      # - name: Deploy to Azure Web App
      #   id: deploy-to-webapp
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: "${{ env.AZURE_WEBAPP_NAME }} dev"
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  

